<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CreateCustomer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2576074a-eab6-4b42-8ec6-334a30e4c55d</testSuiteGuid>
   <testCaseLink>
      <guid>617e016f-9778-4967-800f-dd36b0245d71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pratice_B3/Ontap</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0b17789e-3ded-4495-a750-1fb622af676b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/list email</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4933bb23-5b4f-46fa-9f9d-11ddd0751b0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dee86732-a747-4c38-98bb-3cd24f316fad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>806cf93e-c551-4b0f-860d-7acf3a977d29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c70e7166-f74c-49cb-be91-cd9d1488b2ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>208c1830-4598-4160-95f3-12d7b571738f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b17789e-3ded-4495-a750-1fb622af676b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>aca25118-3764-46c1-8f18-6252284d0327</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0537dda8-d56b-4eac-a41a-ea0f880438a8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
